<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MARS login</name>
   <tag></tag>
   <elementGuidId>41d008b9-8a6f-4e47-9350-3a80ca10b85c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-mainnavigation']/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>617d67d3-556e-4391-881b-42af4da11147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://recovery.qldra.org.au/auth/login?returnUrl=/home/welcome</value>
      <webElementGuid>b97e1d1f-81ec-4299-b202-4b77da1707de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MARS login </value>
      <webElementGuid>8eb6ac40-72c2-49f0-8dab-f24a0c7b7303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-mainnavigation&quot;)/ul[@class=&quot;menu sm&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>d283b95f-ae3c-4363-8254-b7e78bca940a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-mainnavigation']/ul/li[9]/a</value>
      <webElementGuid>c296d9da-1752-4802-af60-9b3e96bd580f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MARS login')]</value>
      <webElementGuid>e343e932-ec23-4682-8588-aaae16dd6228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QRA e-newsletter'])[1]/following::a[2]</value>
      <webElementGuid>e0096f00-8ce7-45c0-9a6b-c8bbbe318ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured videos'])[1]/following::a[3]</value>
      <webElementGuid>40c22408-3952-42cb-871e-ca275cbe03ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top menu'])[1]/preceding::a[1]</value>
      <webElementGuid>66cfbb49-c864-45e0-8703-0918c27ca803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site map'])[1]/preceding::a[1]</value>
      <webElementGuid>225d1ee1-7e08-4d5e-9a7c-c9206d5da3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MARS login']/parent::*</value>
      <webElementGuid>7d080a5c-f128-4d58-8416-6c32aff81beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://recovery.qldra.org.au/auth/login?returnUrl=/home/welcome')]</value>
      <webElementGuid>e05c0baa-61ac-471a-b261-c5648bf71b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>38855682-ab02-4ba5-8266-02ae67996c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://recovery.qldra.org.au/auth/login?returnUrl=/home/welcome' and (text() = 'MARS login ' or . = 'MARS login ')]</value>
      <webElementGuid>5c427938-0b89-4cdb-9ae6-7af1c9c02c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
