<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help_search_api_fulltext</name>
   <tag></tag>
   <elementGuidId>b8c09d5a-5aa9-42f5-baa2-9d14f1f5ac05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='edit-search-api-fulltext']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-search-api-fulltext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eac7d0d-507d-496a-8a84-9b7c7527cef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search the QRA...</value>
      <webElementGuid>900e6c83-06e3-4418-9be9-52e9d392d7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-selector</name>
      <type>Main</type>
      <value>edit-search-api-fulltext</value>
      <webElementGuid>acf3047b-1170-4df2-a91a-e057b7fd9468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2190cd71-435b-4144-8bb2-ae383e6ef7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-search-api-fulltext</value>
      <webElementGuid>7a307dd8-bac0-450e-accb-9e57b717a542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_api_fulltext</value>
      <webElementGuid>1d2e5ecc-4428-4d16-9ea1-6f4dce188353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>03008c31-de1f-4243-ae9e-b7c1f88a72cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>60d877b0-7e72-4ea0-81e0-5aa5ce38d7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text</value>
      <webElementGuid>6846be86-54b0-4df9-ba01-b72ff97fc35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-search-api-fulltext&quot;)</value>
      <webElementGuid>b397326d-098a-481e-ae62-63e985594e9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit-search-api-fulltext']</value>
      <webElementGuid>48201f73-49bd-4671-a89b-6383014c97bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='views-exposed-form-ssa-search-page-1']/div/div/input</value>
      <webElementGuid>2224da3e-1144-470c-970f-7515fd79a916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>81e542d9-f9f9-41d9-a694-27556f8369e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search the QRA...' and @type = 'text' and @id = 'edit-search-api-fulltext' and @name = 'search_api_fulltext']</value>
      <webElementGuid>c63a8cbb-bcd8-49e6-8453-4654419dd69a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
