<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_News</name>
   <tag></tag>
   <elementGuidId>d86e3628-9c36-48f3-8971-b7702b90c61a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-qra-content']/div/div/div[2]/div/div/div/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6622d42d-1e81-4a78-a5cd-7be41d526ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news-case-studies/news</value>
      <webElementGuid>89866097-9b2b-470c-9168-13751131e1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hreflang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>7f134fb0-3bbd-455f-bade-01249e7e5061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>6f8a52b9-9bf4-4728-9021-845b1f0144a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-qra-content&quot;)/div[@class=&quot;views-element-container&quot;]/div[@class=&quot;view view-ssa-search view-id-ssa_search view-display-id-page_1 js-view-dom-id-0f9766fcdfdc6fc2e785c57e0b9876239623851fd7ff7d324c9318ab17290e9e&quot;]/div[@class=&quot;view-content&quot;]/div[@class=&quot;views-row&quot;]/div[@class=&quot;node node--type-content-page node--view-mode-search-index ds-1col clearfix&quot;]/div[@class=&quot;main-page-content&quot;]/div[@class=&quot;field field--name-node-title field--type-ds field--label-hidden field__item&quot;]/p[1]/a[1]</value>
      <webElementGuid>ad07311e-1416-41d4-bb9f-0e64ffddc51f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-qra-content']/div/div/div[2]/div/div/div/div/p/a</value>
      <webElementGuid>99ddf45b-697e-41a0-9d1e-54b4b57686a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'News')])[3]</value>
      <webElementGuid>4523c8f0-bf70-4f48-b231-9f475ff7255a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displaying 1 - 10 of 38'])[1]/following::a[1]</value>
      <webElementGuid>76863643-807d-43fe-ab13-02e28e934c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>8c48005b-213b-4d57-8623-aaea066d60e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QRA e-newsletter'])[2]/preceding::a[1]</value>
      <webElementGuid>1b78a2fa-deb0-46c8-9613-230608889ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gulf Group improving healthy waterways in Carpentaria'])[1]/preceding::a[2]</value>
      <webElementGuid>762b011f-e500-4465-befa-92bc352a7b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/news-case-studies/news')])[2]</value>
      <webElementGuid>153e572d-fca1-4519-9e34-5b90676ba299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>0dc86ef1-550b-4cce-9acf-36ec3dc84ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news-case-studies/news' and (text() = 'News' or . = 'News')]</value>
      <webElementGuid>59d3ebce-25b0-4d37-be05-7d4ff1fe57b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
